services:
    Elbformat\FieldHelperBundle\Registry\RegistryInterface: '@elbformat_field_helper.registry'

    elbformat_field_helper.registry:
        class: Elbformat\FieldHelperBundle\Registry\Registry

    elbformat_field_helper.field_helper.author:
        class: Elbformat\FieldHelperBundle\FieldHelper\AuthorFieldHelper
        tags: ['elbformat_field_helper.field_helper']

    elbformat_field_helper.field_helper.bool:
        class: Elbformat\FieldHelperBundle\FieldHelper\BoolFieldHelper
        tags: ['elbformat_field_helper.field_helper']

    elbformat_field_helper.field_helper.datetime:
        class: Elbformat\FieldHelperBundle\FieldHelper\DateTimeFieldHelper
        tags: ['elbformat_field_helper.field_helper']

    elbformat_field_helper.field_helper.file:
        class: Elbformat\FieldHelperBundle\FieldHelper\FileFieldHelper
        tags: ['elbformat_field_helper.field_helper']

    elbformat_field_helper.field_helper.image:
        class: Elbformat\FieldHelperBundle\FieldHelper\ImageFieldHelper
        tags: ['elbformat_field_helper.field_helper']
        arguments:
            $variationHandler: '@eZ\Publish\SPI\Variation\VariationHandler'
            $repo: '@ezpublish.api.repository'
            $config: '@ezpublish.config.resolver'
            $responseTagger: '@EzSystems\PlatformHttpCacheBundle\ResponseTagger\ResponseTagger'
            $fhRichtext: '@elbformat_field_helper.field_helper.richtext'
            $fhRel: '@elbformat_field_helper.field_helper.relation'

# Loaded dynmically, only if bundle is installed
#    elbformat_field_helper.field_helper.netgentags:
#        class: Elbformat\FieldHelperBundle\FieldHelper\NetgenTagsFieldHelper
#        tags: ['elbformat_field_helper.field_helper']
#        arguments:
#            $tagsService: '@eztags.api.service.tags'

    elbformat_field_helper.field_helper.number:
        class: Elbformat\FieldHelperBundle\FieldHelper\NumberFieldHelper
        tags: ['elbformat_field_helper.field_helper']

    elbformat_field_helper.field_helper.relation:
        class: Elbformat\FieldHelperBundle\FieldHelper\RelationFieldHelper
        arguments:
            $repo: '@eZ\Publish\API\Repository\Repository'
            $responseTagger: '@ezplatform.view_cache.response_tagger.dispatcher'
            $logger: '@logger'
        tags: ['elbformat_field_helper.field_helper']

    elbformat_field_helper.field_helper.richtext:
        class: Elbformat\FieldHelperBundle\FieldHelper\RichtextFieldHelper
        arguments:
            $fieldHelper: '@ezpublish.field_helper'
            $richtextConverter: '@ezrichtext.converter.output.xhtml5'
        tags: ['elbformat_field_helper.field_helper']

    elbformat_field_helper.field_helper.selection:
        class: Elbformat\FieldHelperBundle\FieldHelper\SelectionFieldHelper
        tags: ['elbformat_field_helper.field_helper']

    elbformat_field_helper.field_helper.text:
        class: Elbformat\FieldHelperBundle\FieldHelper\TextFieldHelper
        tags: ['elbformat_field_helper.field_helper']

    elbformat_field_helper.field_helper.url:
        class: Elbformat\FieldHelperBundle\FieldHelper\UrlFieldHelper
        tags: ['elbformat_field_helper.field_helper']

