services:
    Elbformat\FieldHelperBundle\Registry\RegistryInterface: '@elbformat_field_helper.registry'

    elbformat_field_helper.registry:
        class: Elbformat\FieldHelperBundle\Registry\Registry

    elbformat_field_helper.field_helper.bool:
        class: Elbformat\FieldHelperBundle\FieldHelper\BoolFieldHelper
        tags: ['elbformat_field_helper.field_helper']

    elbformat_field_helper.field_helper.datetime:
        class: Elbformat\FieldHelperBundle\FieldHelper\DateTimeFieldHelper
        tags: ['elbformat_field_helper.field_helper']

    elbformat_field_helper.field_helper.number:
        class: Elbformat\FieldHelperBundle\FieldHelper\NumberFieldHelper
        tags: ['elbformat_field_helper.field_helper']

    elbformat_field_helper.field_helper.relation:
        class: Elbformat\FieldHelperBundle\FieldHelper\RelationFieldHelper
        arguments:
            $repo: '@eZ\Publish\API\Repository\Repository'
            $responseTagger: '@ezplatform.view_cache.response_tagger.dispatcher'
            $logger: '@logger'
        tags: ['elbformat_field_helper.field_helper']

    elbformat_field_helper.field_helper.text:
        class: Elbformat\FieldHelperBundle\FieldHelper\TextFieldHelper
        tags: ['elbformat_field_helper.field_helper']

    elbformat_field_helper.field_helper.url:
        class: Elbformat\FieldHelperBundle\FieldHelper\UrlFieldHelper
        tags: ['elbformat_field_helper.field_helper']
