services:
    Elbformat\FieldHelperBundle\Registry\RegistryInterface: '@elbformat_field_helper.registry'

    elbformat_field_helper.registry:
        class: Elbformat\FieldHelperBundle\Registry\Registry
        arguments:
            $helper: []

    elbformat_field_helper.field_helper.text:
        class: Elbformat\FieldHelperBundle\FieldHelper\TextFieldHelper
        tags: ['elbformat_field_helper.field_helper']