services:
    Elbformat\IbexaFieldHelperBundle\Registry\RegistryInterface: '@elbformat_ibexa_field_helper.registry'

    elbformat_ibexa_field_helper.registry:
        class: Elbformat\IbexaFieldHelperBundle\Registry\Registry
        arguments:
            $helper: []
